import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tyler
 */
public class AMSGU extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AMSGUI.class.getName());

    // manager objects
    private PassengerManagment passengerManager = new PassengerManagment();
    private StaffManagment staffManager = new StaffManagment();

    /**
     * Creates new form AMSGUI
     */
    public AMSGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        loadDummyButton = new javax.swing.JButton();
        viewPassengersButton = new javax.swing.JButton();
        viewStaffButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        titleLabel.setText("Airline Management System");

        loadDummyButton.setText("Load Dummy Data");
        loadDummyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDummyButtonActionPerformed(evt);
            }
        });

        viewPassengersButton.setText("View Passengers");
        viewPassengersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPassengersButtonActionPerformed(evt);
            }
        });

        viewStaffButton.setText("View Staff");
        viewStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStaffButtonActionPerformed(evt);
            }
        });

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadDummyButton)
                        .addGap(18, 18, 18)
                        .addComponent(viewPassengersButton)
                        .addGap(18, 18, 18)
                        .addComponent(viewStaffButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadDummyButton)
                    .addComponent(viewPassengersButton)
                    .addComponent(viewStaffButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }

    private void loadDummyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        passengerManager.loadDummyPassengers();
        staffManager.loadDummyStaff();
        outputArea.setText("Dummy data loaded successfully.\n\nUse View Passengers or View Staff to see the records.");
    }

    private void viewPassengersButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String text = "----- PASSENGERS -----\n";

        Passenger p1 = passengerManager.searchPassengerById(101);
        Passenger p2 = passengerManager.searchPassengerById(102);
        Passenger p3 = passengerManager.searchPassengerById(103);

        boolean foundAny = false;

        if (p1 != null) {
            text += p1.toString() + "\n-------------------------\n";
            foundAny = true;
        }
        if (p2 != null) {
            text += p2.toString() + "\n-------------------------\n";
            foundAny = true;
        }
        if (p3 != null) {
            text += p3.toString() + "\n-------------------------\n";
            foundAny = true;
        }

        if (!foundAny) {
            text += "No passengers found.";
        }

        outputArea.setText(text);
    }

    private void viewStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String text = "----- STAFF -----\n";

        Staff s1 = staffManager.searchStaffById(201);
        Staff s2 = staffManager.searchStaffById(202);
        Staff s3 = staffManager.searchStaffById(203);

        boolean foundAny = false;

        if (s1 != null) {
            text += s1.toString() + "\n-------------------------\n";
            foundAny = true;
        }
        if (s2 != null) {
            text += s2.toString() + "\n-------------------------\n";
            foundAny = true;
        }
        if (s3 != null) {
            text += s3.toString() + "\n-------------------------\n";
            foundAny = true;
        }

        if (!foundAny) {
            text += "No staff members found.";
        }

        outputArea.setText(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new AMSGUI().setVisible(true));
    }

    // Variables declaration
    private javax.swing.JButton loadDummyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewPassengersButton;
    private javax.swing.JButton viewStaffButton;
    // End of variables declaration
}
