import java.awt.GridLayout;
import java.time.LocalDate;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tyler
 */
public class BookingMenu extends javax.swing.JFrame 
{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingMenu.class.getName());

    static AirlineManagement airlineMgmt = new AirlineManagement();
    static StaffManagment staffManager = new StaffManagment();
    private PassengerManagment passengerManager = new PassengerManagment();
    private ScheduleManagement scheduleMgmt = new ScheduleManagement();
    private DefaultTableModel tableModel;
    private TicketManagement ticketMgmt = new TicketManagement(scheduleMgmt, passengerManager);
    
    /**
     * Creates new form BookingMenu
     */
    public BookingMenu(TicketManagement ticketMgmt, PassengerManagment passengerManager, ScheduleManagement scheduleMgmt, AirlineManagement airlineMgmt, StaffManagment staffManager) 
    {
        this.ticketMgmt = ticketMgmt;
        this.passengerManager = passengerManager;
        this.scheduleMgmt = scheduleMgmt;
        this.staffManager = staffManager;
        this.airlineMgmt = airlineMgmt;
    
        initComponents();
        setLocationRelativeTo(null);
        setupTable();
        loadTickets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Menu");
        setName("BookingMenu"); // NOI18N

        btnCreate.setText("Create Ticket");
        btnCreate.setName("btnCreate"); // NOI18N
        btnCreate.addActionListener(this::btnCreateActionPerformed);

        btnView.setText("View Ticket");
        btnView.setName("btnView"); // NOI18N
        btnView.addActionListener(this::btnViewActionPerformed);

        btnBack.setText("Back");
        btnBack.setName("btnBack"); // NOI18N
        btnBack.addActionListener(this::btnBackActionPerformed);

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ticketTable.setName("ticketTable"); // NOI18N
        jScrollPane1.setViewportView(ticketTable);
        ticketTable.getAccessibleContext().setAccessibleName("ticketTable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCreate.getAccessibleContext().setAccessibleName("btnCreate");
        btnCreate.getAccessibleContext().setAccessibleDescription("");
        btnView.getAccessibleContext().setAccessibleName("btnView");
        btnBack.getAccessibleContext().setAccessibleName("btnBack");
        btnBack.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        openCreateTicketForm();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        loadTickets();
        showTickets();
        ticketMessage();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new PassengerMenu(ticketMgmt, passengerManager, scheduleMgmt, airlineMgmt, staffManager).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void setupTable()
    {
        String[] columns = {"Ticket #", "Passenger", "Class", "Date", "Destination", "Price", "Airline"};
        tableModel = new DefaultTableModel(columns, 0);
        ticketTable.setModel(tableModel);
    }
    
    private void loadTickets() 
    {
        tableModel.setRowCount(0);

        for (Ticket t : ticketMgmt.getTickets()) 
        {
            tableModel.addRow(new Object[]
            {
                t.getTicketNumber(),
                t.getPassenger().getFirstName() + " " + t.getPassenger().getLastName(),
                t.getFlightClass(),
                t.getFlightDate(),
                t.getFlight().getDestination(),
                "$100",
                "Eduardo Airlines"
            });
        }
    }
    
    private void showTickets() 
    {
        String input = JOptionPane.showInputDialog(null, "Enter Ticket Number:");

        if (input == null || input.trim().isEmpty()) 
        {
            return; 
        }

        int ticketNumber;

        try 
        {
            ticketNumber = Integer.parseInt(input.trim());
        } 
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Invalid ticket number.");
            return;
        }

        for (Ticket t : ticketMgmt.getTickets()) 
        {
            if (t.getTicketNumber() == ticketNumber) 
            {
                showTicketWindow(t);
                return;
            }
        }
    }
    
    private void showTicketWindow(Ticket t)
    {
        JDialog dialog = new JDialog();
        dialog.setTitle("Ticket Details");
        dialog.setSize(350, 300);
        dialog.setLocationRelativeTo(null);
        dialog.setModal(true);

        JTextArea text = new JTextArea();
        text.setEditable(false);
        text.setText(
            "Ticket Number: " + t.getTicketNumber() + "\n" +
            "Passenger: " + t.getPassenger().getFirstName() + " " + t.getPassenger().getLastName() + "\n" +
            "Class: " + t.getFlightClass() + "\n" +
            "Flight Date: " + t.getFlightDate() + "\n" +
            "Destination: " + t.getFlight().getDestination() + "\n" +
            "Price: $100\n" +
            "Airline: Eduardo Airlines"
    );

    dialog.add(new JScrollPane(text));
    dialog.setVisible(true);
}
    
    private void ticketMessage()
    {
        if (ticketMgmt.getTickets().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this,
                    "No tickets available.",
                    "Ticket List",
                    JOptionPane.INFORMATION_MESSAGE);
            tableModel.setRowCount(0); 
            return;
        }
    }
    
    private void openCreateTicketForm() 
    {
        JTextField passengerIdField = new JTextField();

        String[] classes = {"Economy", "Business", "First Class"};
        JComboBox<String> classBox = new JComboBox<>(classes);

        String[] destinations = {"Honolulu HI", "Fairbanks AK"};
        JComboBox<String> destinationBox = new JComboBox<>(destinations);

        JTextField priceField = new JTextField("$100");
        priceField.setEditable(false);

        JTextField airlineField = new JTextField("Eduardo Airlines");
        airlineField.setEditable(false);

        JTextField dateField = new JTextField(LocalDate.now().toString());
        dateField.setEditable(false);

        JPanel form = new JPanel(new GridLayout(0, 2));
        form.add(new JLabel("Passenger ID:"));
        form.add(passengerIdField);
        form.add(new JLabel("Flight Class:"));
        form.add(classBox);
        form.add(new JLabel("Destination:"));
        form.add(destinationBox);
        form.add(new JLabel("Price:"));
        form.add(priceField);
        form.add(new JLabel("Airline:"));
        form.add(airlineField);
        form.add(new JLabel("Date (Today):"));
        form.add(dateField);

        int result = JOptionPane.showConfirmDialog(
            this, form, "Create Ticket", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) 
        {
            try 
            {
                String pidText = passengerIdField.getText().trim();
                if (pidText.isEmpty()) 
                {
                    JOptionPane.showMessageDialog(this, "Please enter a Passenger ID.");
                    return;
                }

                int pid;
                try 
                {
                    pid = Integer.parseInt(pidText);
                } 
                catch (NumberFormatException e) 
                {
                    JOptionPane.showMessageDialog(this, "Passenger ID must be a number.");
                    return;
                }

                Passenger passenger = passengerManager.searchPassengerById(pid);
                if (passenger == null) 
                {
                    JOptionPane.showMessageDialog(this, "Passenger not found!");
                    return;
                }

                int ticketNum = ticketMgmt.generateTicketNumber();

                float price = 100;
                LocalDate date = LocalDate.now();
                String fClass = classBox.getSelectedItem().toString();
                String dest = destinationBox.getSelectedItem().toString();

                Flight f = new Flight(dest, "Portales NM", (short)3000, (short)800);

                Ticket t = new Ticket(
                    ticketNum,
                    price,
                    fClass,
                    date,
                    f,
                    passenger,
                    scheduleMgmt.getDepartureTime(),
                    scheduleMgmt.getArrivalTime(),
                    scheduleMgmt.getBoardingTime()
                );

                ticketMgmt.addTicket(t);
                ticketMgmt.saveTicketsToFile();
                JOptionPane.showMessageDialog(this, "Ticket Created!");
                loadTickets();
            } 
            catch (Exception ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Invalid input. Try again.");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ticketTable;
    // End of variables declaration//GEN-END:variables
}
