/**
 *
 * @author tyler
 */
public class MainMenu extends javax.swing.JFrame 
{ 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());
    
    static AirlineManagement airlineMgmt = new AirlineManagement();
    static StaffManagment staffManager = new StaffManagment();
    static ScheduleManagement scheduleMgmt = new ScheduleManagement();
    static PassengerManagment passengerManager = new PassengerManagment();
    static TicketManagement ticketMgmt = new TicketManagement(scheduleMgmt, passengerManager);
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu(TicketManagement ticketMgmt, PassengerManagment passengerManager, ScheduleManagement scheduleMgmt, AirlineManagement airlineMgmt, StaffManagment staffManager) 
    {
        this.passengerManager = passengerManager;
        this.scheduleMgmt = scheduleMgmt;
        this.staffManager = staffManager;
        this.airlineMgmt = airlineMgmt;
    
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Main Menu");
        setName("MainMenu");

        lblTitle = new javax.swing.JLabel();
        btnPassengerMenu = new javax.swing.JButton();
        btnStaffMenu = new javax.swing.JButton();
        btnAdminMenu = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText(" Eduardo Airline Management System");
        lblTitle.setToolTipText("");
        lblTitle.setName("lblTitle"); // NOI18N

        btnPassengerMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPassengerMenu.setText("Passenger Menu");
        btnPassengerMenu.setToolTipText("");
        btnPassengerMenu.setName("btnPassengerMenu"); // NOI18N
        btnPassengerMenu.addActionListener(this::btnPassengerMenuActionPerformed);

        btnStaffMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStaffMenu.setText("Staff Menu");
        btnStaffMenu.setToolTipText("");
        btnStaffMenu.setName("btnStaffMenu"); // NOI18N
        btnStaffMenu.addActionListener(this::btnStaffMenuActionPerformed);

        btnAdminMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdminMenu.setText("Admin Menu");
        btnAdminMenu.setToolTipText("");
        btnAdminMenu.setName("btnAdminMenu"); // NOI18N
        btnAdminMenu.addActionListener(this::btnAdminMenuActionPerformed);

        btnQuit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("");
        btnQuit.setName("btnQuit"); // NOI18N
        btnQuit.addActionListener(this::btnQuitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaffMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPassengerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPassengerMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaffMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPassengerMenuActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_btnPassengerMenuActionPerformed
        new PassengerMenu(ticketMgmt, passengerManager, scheduleMgmt, airlineMgmt, staffManager).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPassengerMenuActionPerformed
    
    private void btnStaffMenuActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_btnStaffMenuActionPerformed
        while (true) 
        {
            String password = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Enter password (or type 'back' to cancel):"
            );

            if (password == null) {
                return;
            }

            password = password.trim();

            if (password.equalsIgnoreCase("back")) 
            {
                return;
            }

            if (password.equalsIgnoreCase("eduardo")) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Access granted.");
                new StaffMenu(ticketMgmt, passengerManager, scheduleMgmt, airlineMgmt, staffManager).setVisible(true);
                this.setVisible(false);
                return;
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "Incorrect password. Try again.");
        }
    }//GEN-LAST:event_btnStaffMenuActionPerformed

    private void btnAdminMenuActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_btnAdminMenuActionPerformed
        while (true) 
        {
            String password = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Enter password (or type 'back' to cancel):"
            );

            if (password == null) 
            {
                return;
            }

            password = password.trim();

            if (password.equalsIgnoreCase("back")) 
            {
                return;
            }

            if (password.equalsIgnoreCase("eduardo")) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Access granted.");
                new AdminMenu(ticketMgmt, passengerManager, scheduleMgmt, airlineMgmt, staffManager).setVisible(true);
                this.setVisible(false);
                return;
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Incorrect password. Try again.");
        }
    }//GEN-LAST:event_btnAdminMenuActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminMenu;
    private javax.swing.JButton btnPassengerMenu;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStaffMenu;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
